package org.dominokit.domino.colors.client.views.ui;

import elemental2.dom.HTMLDivElement;
import elemental2.dom.HTMLElement;
import org.dominokit.domino.api.client.annotations.UiView;
import org.dominokit.domino.colors.client.presenters.ColorsPresenter;
import org.dominokit.domino.colors.client.views.ColorsView;
import org.dominokit.domino.componentcase.shared.extension.ComponentView;
import org.dominokit.domino.ui.cards.Card;
import org.dominokit.domino.ui.column.Column;
import org.dominokit.domino.ui.header.BlockHeader;
import org.dominokit.domino.ui.row.Row;
import org.dominokit.domino.ui.style.Color;
import org.dominokit.domino.ui.style.ColorScheme;

import static org.jboss.gwt.elemento.core.Elements.a;
import static org.jboss.gwt.elemento.core.Elements.div;

@UiView(presentable = ColorsPresenter.class)
public class ColorsViewImpl extends ComponentView<HTMLDivElement> implements ColorsView {

    private HTMLDivElement element = div().asElement();

    @Override
    public HTMLDivElement getElement() {
        return element;
    }

    @Override
    public void init() {
        element.appendChild(BlockHeader.create("COLORS").asElement());

        Column column = Column.create()
                .onLarge(Column.OnLarge.three)
                .onMedium(Column.OnMedium.three)
                .onSmall(Column.OnSmall.twelve)
                .onXSmall(Column.OnXSmall.twelve);

        element.appendChild(Card.create("MATERIAL DESIGN COLORS", "Taken by Google's Material Design Color page which link is ")
                .appendDescriptionContent(a()
                        .attr("href", "https://material.google.com/style/color.html#color-color-palette")
                        .textContent("material.google.com/style/color.html#color-color-palette")
                        .title("Google's Material Design Color").asElement())
                .appendContent(Row.create()
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.RED.darker_4()))
                                .addElement(makeColorBox(ColorScheme.RED.darker_3()))
                                .addElement(makeColorBox(ColorScheme.RED.darker_2()))
                                .addElement(makeColorBox(ColorScheme.RED.darker_1()))
                                .addElement(makeColorBox(Color.RED))
                                .addElement(makeColorBox(ColorScheme.RED.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.RED.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.RED.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.RED.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.RED.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.PINK.darker_4()))
                                .addElement(makeColorBox(ColorScheme.PINK.darker_3()))
                                .addElement(makeColorBox(ColorScheme.PINK.darker_2()))
                                .addElement(makeColorBox(ColorScheme.PINK.darker_1()))
                                .addElement(makeColorBox(Color.PINK))
                                .addElement(makeColorBox(ColorScheme.PINK.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.PINK.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.PINK.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.PINK.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.PINK.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.PURPLE.darker_4()))
                                .addElement(makeColorBox(ColorScheme.PURPLE.darker_3()))
                                .addElement(makeColorBox(ColorScheme.PURPLE.darker_2()))
                                .addElement(makeColorBox(ColorScheme.PURPLE.darker_1()))
                                .addElement(makeColorBox(Color.PURPLE))
                                .addElement(makeColorBox(ColorScheme.PURPLE.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.PURPLE.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.PURPLE.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.PURPLE.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.PURPLE.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.DEEP_PURPLE.darker_4()))
                                .addElement(makeColorBox(ColorScheme.DEEP_PURPLE.darker_3()))
                                .addElement(makeColorBox(ColorScheme.DEEP_PURPLE.darker_2()))
                                .addElement(makeColorBox(ColorScheme.DEEP_PURPLE.darker_1()))
                                .addElement(makeColorBox(Color.DEEP_PURPLE))
                                .addElement(makeColorBox(ColorScheme.DEEP_PURPLE.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.DEEP_PURPLE.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.DEEP_PURPLE.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.DEEP_PURPLE.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.DEEP_PURPLE.lighten_5()))
                        )

                        .asElement())
                .appendContent(Row.create()
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.INDIGO.darker_4()))
                                .addElement(makeColorBox(ColorScheme.INDIGO.darker_3()))
                                .addElement(makeColorBox(ColorScheme.INDIGO.darker_2()))
                                .addElement(makeColorBox(ColorScheme.INDIGO.darker_1()))
                                .addElement(makeColorBox(Color.INDIGO))
                                .addElement(makeColorBox(ColorScheme.INDIGO.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.INDIGO.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.INDIGO.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.INDIGO.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.INDIGO.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.BLUE.darker_4()))
                                .addElement(makeColorBox(ColorScheme.BLUE.darker_3()))
                                .addElement(makeColorBox(ColorScheme.BLUE.darker_2()))
                                .addElement(makeColorBox(ColorScheme.BLUE.darker_1()))
                                .addElement(makeColorBox(Color.BLUE))
                                .addElement(makeColorBox(ColorScheme.BLUE.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.BLUE.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.BLUE.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.BLUE.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.BLUE.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.LIGHT_BLUE.darker_4()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_BLUE.darker_3()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_BLUE.darker_2()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_BLUE.darker_1()))
                                .addElement(makeColorBox(Color.LIGHT_BLUE))
                                .addElement(makeColorBox(ColorScheme.LIGHT_BLUE.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_BLUE.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_BLUE.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_BLUE.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_BLUE.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.CYAN.darker_4()))
                                .addElement(makeColorBox(ColorScheme.CYAN.darker_3()))
                                .addElement(makeColorBox(ColorScheme.CYAN.darker_2()))
                                .addElement(makeColorBox(ColorScheme.CYAN.darker_1()))
                                .addElement(makeColorBox(Color.CYAN))
                                .addElement(makeColorBox(ColorScheme.CYAN.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.CYAN.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.CYAN.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.CYAN.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.CYAN.lighten_5()))
                        )
                        .asElement())
                .appendContent(Row.create()
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.TEAL.darker_4()))
                                .addElement(makeColorBox(ColorScheme.TEAL.darker_3()))
                                .addElement(makeColorBox(ColorScheme.TEAL.darker_2()))
                                .addElement(makeColorBox(ColorScheme.TEAL.darker_1()))
                                .addElement(makeColorBox(Color.TEAL))
                                .addElement(makeColorBox(ColorScheme.TEAL.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.TEAL.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.TEAL.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.TEAL.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.TEAL.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.GREEN.darker_4()))
                                .addElement(makeColorBox(ColorScheme.GREEN.darker_3()))
                                .addElement(makeColorBox(ColorScheme.GREEN.darker_2()))
                                .addElement(makeColorBox(ColorScheme.GREEN.darker_1()))
                                .addElement(makeColorBox(Color.GREEN))
                                .addElement(makeColorBox(ColorScheme.GREEN.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.GREEN.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.GREEN.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.GREEN.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.GREEN.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.LIGHT_GREEN.darker_4()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_GREEN.darker_3()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_GREEN.darker_2()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_GREEN.darker_1()))
                                .addElement(makeColorBox(Color.LIGHT_GREEN))
                                .addElement(makeColorBox(ColorScheme.LIGHT_GREEN.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_GREEN.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_GREEN.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_GREEN.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.LIGHT_GREEN.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.LIME.darker_4()))
                                .addElement(makeColorBox(ColorScheme.LIME.darker_3()))
                                .addElement(makeColorBox(ColorScheme.LIME.darker_2()))
                                .addElement(makeColorBox(ColorScheme.LIME.darker_1()))
                                .addElement(makeColorBox(Color.LIME))
                                .addElement(makeColorBox(ColorScheme.LIME.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.LIME.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.LIME.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.LIME.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.LIME.lighten_5()))
                        )
                        .asElement())
                .appendContent(Row.create()
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.YELLOW.darker_4()))
                                .addElement(makeColorBox(ColorScheme.YELLOW.darker_3()))
                                .addElement(makeColorBox(ColorScheme.YELLOW.darker_2()))
                                .addElement(makeColorBox(ColorScheme.YELLOW.darker_1()))
                                .addElement(makeColorBox(Color.YELLOW))
                                .addElement(makeColorBox(ColorScheme.YELLOW.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.YELLOW.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.YELLOW.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.YELLOW.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.YELLOW.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.AMBER.darker_4()))
                                .addElement(makeColorBox(ColorScheme.AMBER.darker_3()))
                                .addElement(makeColorBox(ColorScheme.AMBER.darker_2()))
                                .addElement(makeColorBox(ColorScheme.AMBER.darker_1()))
                                .addElement(makeColorBox(Color.AMBER))
                                .addElement(makeColorBox(ColorScheme.AMBER.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.AMBER.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.AMBER.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.AMBER.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.AMBER.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.ORANGE.darker_4()))
                                .addElement(makeColorBox(ColorScheme.ORANGE.darker_3()))
                                .addElement(makeColorBox(ColorScheme.ORANGE.darker_2()))
                                .addElement(makeColorBox(ColorScheme.ORANGE.darker_1()))
                                .addElement(makeColorBox(Color.ORANGE))
                                .addElement(makeColorBox(ColorScheme.ORANGE.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.ORANGE.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.ORANGE.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.ORANGE.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.ORANGE.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.DEEP_ORANGE.darker_4()))
                                .addElement(makeColorBox(ColorScheme.DEEP_ORANGE.darker_3()))
                                .addElement(makeColorBox(ColorScheme.DEEP_ORANGE.darker_2()))
                                .addElement(makeColorBox(ColorScheme.DEEP_ORANGE.darker_1()))
                                .addElement(makeColorBox(Color.DEEP_ORANGE))
                                .addElement(makeColorBox(ColorScheme.DEEP_ORANGE.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.DEEP_ORANGE.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.DEEP_ORANGE.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.DEEP_ORANGE.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.DEEP_ORANGE.lighten_5()))
                        )
                        .asElement())
                .appendContent(Row.create()
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.BROWN.darker_4()))
                                .addElement(makeColorBox(ColorScheme.BROWN.darker_3()))
                                .addElement(makeColorBox(ColorScheme.BROWN.darker_2()))
                                .addElement(makeColorBox(ColorScheme.BROWN.darker_1()))
                                .addElement(makeColorBox(Color.BROWN))
                                .addElement(makeColorBox(ColorScheme.BROWN.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.BROWN.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.BROWN.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.BROWN.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.BROWN.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.GREY.darker_4()))
                                .addElement(makeColorBox(ColorScheme.GREY.darker_3()))
                                .addElement(makeColorBox(ColorScheme.GREY.darker_2()))
                                .addElement(makeColorBox(ColorScheme.GREY.darker_1()))
                                .addElement(makeColorBox(Color.GREY))
                                .addElement(makeColorBox(ColorScheme.GREY.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.GREY.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.GREY.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.GREY.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.GREY.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.BLUE_GREY.darker_4()))
                                .addElement(makeColorBox(ColorScheme.BLUE_GREY.darker_3()))
                                .addElement(makeColorBox(ColorScheme.BLUE_GREY.darker_2()))
                                .addElement(makeColorBox(ColorScheme.BLUE_GREY.darker_1()))
                                .addElement(makeColorBox(Color.BLUE_GREY))
                                .addElement(makeColorBox(ColorScheme.BLUE_GREY.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.BLUE_GREY.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.BLUE_GREY.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.BLUE_GREY.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.BLUE_GREY.lighten_5()))
                        )
                        .addColumn(column.copy()
                                .addElement(makeColorBox(ColorScheme.BLACK.darker_4()))
                                .addElement(makeColorBox(ColorScheme.BLACK.darker_3()))
                                .addElement(makeColorBox(ColorScheme.BLACK.darker_2()))
                                .addElement(makeColorBox(ColorScheme.BLACK.darker_1()))
                                .addElement(makeColorBox(Color.BLACK))
                                .addElement(makeColorBox(ColorScheme.BLACK.lighten_1()))
                                .addElement(makeColorBox(ColorScheme.BLACK.lighten_2()))
                                .addElement(makeColorBox(ColorScheme.BLACK.lighten_3()))
                                .addElement(makeColorBox(ColorScheme.BLACK.lighten_4()))
                                .addElement(makeColorBox(ColorScheme.BLACK.lighten_5()))
                        )
                        .asElement())
                .asElement());
    }

    private HTMLElement makeColorBox(Color color) {
        return div().css("demo-color-box", color.getBackground())
                .add(div().css("color-name").textContent(color.getName()))
                .add(div().css("color-code").textContent(color.getHex()))
                .add(div().css("color-class-name").textContent(color.getBackground()))
                .add(div().css("color-class-name").textContent(color.getStyle()))
                .asElement();
    }

}